/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class weblx_browser_Win32 */

#ifndef _Included_weblx_browser_Win32
#define _Included_weblx_browser_Win32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     weblx_browser_Win32
 * Method:    DDERequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_weblx_browser_Win32_DDERequest
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     weblx_browser_Win32
 * Method:    ShellExec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_weblx_browser_Win32_ShellExec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
