/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.parser;

import com.geekstakulus.json.node.*;
import com.geekstakulus.json.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTNumber(TNumber node)
    {
        index = 0;
    }

    public void caseTString(TString node)
    {
        index = 1;
    }

    public void caseTComma(TComma node)
    {
        index = 2;
    }

    public void caseTLCurlyBracket(TLCurlyBracket node)
    {
        index = 3;
    }

    public void caseTRCurlyBracket(TRCurlyBracket node)
    {
        index = 4;
    }

    public void caseTLBracket(TLBracket node)
    {
        index = 5;
    }

    public void caseTRBracket(TRBracket node)
    {
        index = 6;
    }

    public void caseTTrue(TTrue node)
    {
        index = 7;
    }

    public void caseTFalse(TFalse node)
    {
        index = 8;
    }

    public void caseTNull(TNull node)
    {
        index = 9;
    }

    public void caseTColon(TColon node)
    {
        index = 10;
    }

    public void caseEOF(EOF node)
    {
        index = 11;
    }
}
