/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.node;

import java.util.*;
import com.geekstakulus.json.analysis.*;

public final class AArrayValue extends PValue
{
    private final LinkedList _element_ = new TypedLinkedList(new Element_Cast());

    public AArrayValue ()
    {
    }

    public AArrayValue (
            List _element_
    )
    {
        this._element_.clear();
        this._element_.addAll(_element_);
    }

    public Object clone()
    {
        return new AArrayValue (
            cloneList (_element_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayValue(this);
    }

    public LinkedList getElement ()
    {
        return _element_;
    }

    public void setElement (List list)
    {
        _element_.clear();
        _element_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_element_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _element_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _element_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class Element_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PElement node = (PElement) o;

            if((node.parent() != null) &&
                (node.parent() != AArrayValue.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArrayValue.this))
            {
                node.parent(AArrayValue.this);
            }

            return node;
        }
    }
}
