/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.node;

import java.util.*;
import com.geekstakulus.json.analysis.*;

public final class AEmptyElement extends PElement
{


    public AEmptyElement (
    )
    {
    }

    public Object clone()
    {
        return new AEmptyElement (
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyElement(this);
    }


    public String toString()
    {
        return ""
        ;
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

}
