/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.node;

import java.util.*;
import com.geekstakulus.json.analysis.*;

public final class AFalseValue extends PValue
{


    public AFalseValue (
    )
    {
    }

    public Object clone()
    {
        return new AFalseValue (
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFalseValue(this);
    }


    public String toString()
    {
        return ""
        ;
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

}
