/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.node;

import java.util.*;
import com.geekstakulus.json.analysis.*;

public final class AObjectValue extends PValue
{
    private final LinkedList _member_ = new TypedLinkedList(new Member_Cast());

    public AObjectValue ()
    {
    }

    public AObjectValue (
            List _member_
    )
    {
        this._member_.clear();
        this._member_.addAll(_member_);
    }

    public Object clone()
    {
        return new AObjectValue (
            cloneList (_member_)
        );
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjectValue(this);
    }

    public LinkedList getMember ()
    {
        return _member_;
    }

    public void setMember (List list)
    {
        _member_.clear();
        _member_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString (_member_)
        ;
    }

    void removeChild(Node child)
    {
        if ( _member_.remove(child))
        {
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _member_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }
    }

    private class Member_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMember node = (PMember) o;

            if((node.parent() != null) &&
                (node.parent() != AObjectValue.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AObjectValue.this))
            {
                node.parent(AObjectValue.this);
            }

            return node;
        }
    }
}
