/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.node;

public class NoCast implements Cast
{
    public final static NoCast instance = new NoCast();

    private NoCast()
    {
    }

    public Object cast(Object o)
    {
        return o;
    }
}
