/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.node;

import com.geekstakulus.json.analysis.*;

public final class TLCurlyBracket extends Token
{
    public TLCurlyBracket()
    {
        super.setText("{");
    }

    public TLCurlyBracket(int line, int pos)
    {
        super.setText("{");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLCurlyBracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLCurlyBracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLCurlyBracket text.");
    }
}
