/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.node;

import com.geekstakulus.json.analysis.*;

public final class TRCurlyBracket extends Token
{
    public TRCurlyBracket()
    {
        super.setText("}");
    }

    public TRCurlyBracket(int line, int pos)
    {
        super.setText("}");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRCurlyBracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRCurlyBracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRCurlyBracket text.");
    }
}
