/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.geekstakulus.json.analysis;

import com.geekstakulus.json.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAJson(AJson node);
    void caseAObjectValue(AObjectValue node);
    void caseAArrayValue(AArrayValue node);
    void caseANumberValue(ANumberValue node);
    void caseAStringValue(AStringValue node);
    void caseATrueValue(ATrueValue node);
    void caseAFalseValue(AFalseValue node);
    void caseANullValue(ANullValue node);
    void caseAPairMember(APairMember node);
    void caseAEmptyMember(AEmptyMember node);
    void caseAValueElement(AValueElement node);
    void caseAEmptyElement(AEmptyElement node);

    void caseTNumber(TNumber node);
    void caseTString(TString node);
    void caseTComma(TComma node);
    void caseTLCurlyBracket(TLCurlyBracket node);
    void caseTRCurlyBracket(TRCurlyBracket node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTNull(TNull node);
    void caseTColon(TColon node);
    void caseTWhiteSpace(TWhiteSpace node);
    void caseEOF(EOF node);
}
